feat: Changes on geo charts based on UX suggestions
kyndryl-design-system/shidoka-charts pull request #4
Opened 2023-10-23 15:16 UTC by maulik-thaker1

## Summary

1. Added datelabels to US choropleth and Bubble map
2. Flatten world choropleth chart & removed grids
3. Added border width and font size to all geo charts
4. Added zoom plugin for future enhancement

2023-11-02 13:24 UTC, brian-patrick-3 requested changes
>   1. Added datalabels to US choropleth and Bubble map
>   2. Flatten world choropleth chart & removed grids
>   3. Added border width and font size to all geo charts
>   4. Added zoom plugin for future enhancement

1. The datalabels look weird on the Choropleth to me. Also, the value being shown is the scaled value out of 10, not the actual value of the data used to create the chart. Is that really what we intend to show? 
2. Looks cleaner without the globe lines, but kind of stretched.
3. You only added this in the story. If you want it to be a default configuration, you need to add it to the config/chartTypes/json file. Same goes for datalabel changes.
4. I would remove this as a dependency if it's not being used at all.

Remember, US and World Choropleth are the same chart type, and share the same default config. If datalabels is not going into the default config JSON, it should be a separate story.

2023-11-02 13:55 UTC, maulik-thaker1 commented
> > 1. Added datalabels to US choropleth and Bubble map
> > 2. Flatten world choropleth chart & removed grids
> > 3. Added border width and font size to all geo charts
> > 4. Added zoom plugin for future enhancement
> 
> 1. The datalabels look weird on the Choropleth to me. Also, the value being shown is the scaled value out of 10, not the actual value of the data used to create the chart. Is that really what we intend to show?
> 2. Looks cleaner without the globe lines, but kind of stretched.
> 3. You only added this in the story. If you want it to be a default configuration, you need to add it to the config/chartTypes/json file. Same goes for datalabel changes.
> 4. I would remove this as a dependency if it's not being used at all.
> 
> Remember, US and World Choropleth are the same chart type, and share the same default config. If datalabels is not going into the default config JSON, it should be a separate story.

ok I will ask UX guys about these points.

2023-11-02 15:29 UTC, brian-patrick-3 commented
>     2. Yeah kind of but UX wants to keep this.
> 
>     3. ok Do you mean inside **chartArgTypes.js** file?
>        I dont think is default one as world choropleth showing label very oddly

1. We'll probably want to change the labels and the tooltip to show the actual value of the data, rather than the scaled value.
2. Try projection `"equalEarth"`.
3. [These files](https://github.com/kyndryl-design-system/shidoka-charts/tree/beta/src/common/config/chartTypes) are the chart type specific default configs.

2023-11-02 15:51 UTC, maulik-thaker1 commented
> 2\. naturalEarth1



> > ```
> > 2. Yeah kind of but UX wants to keep this.
> > 
> > 3. ok Do you mean inside **chartArgTypes.js** file?
> >    I dont think is default one as world choropleth showing label very oddly
> > ```
> 
> 1. We might want to change the labels and the tooltip to show the actual value of the data, rather than the scaled value.
> 2. Try projection `"equalEarth"` or `"naturalEarth1"` (this should actually probably be the default instead of `"albersUsa"`, since World maps will be more common than US) and `showOutline: false`.
> 3. [These files](https://github.com/kyndryl-design-system/shidoka-charts/tree/beta/src/common/config/chartTypes) are the chartType-specific default configs.

1. there's no actual value in dataset I guess. We are generating random value by giving `value: Math.random() * 10` kind of random value generation
2. If we do projection: "`equalEarth`" and "`naturalEarth1`" then map is not flatten. For flatten world map we need to give '`equirectangular`' only.
3. ok got it.

2023-11-02 16:28 UTC, brian-patrick-3 commented
>     1. there's no actual value in dataset I guess. We are generating random value by giving `value: Math.random() * 10` kind of random value generation
> 
>     2. If we do projection: "`equalEarth`" and "`naturalEarth1`" then map is not gonna flatten. For flatten world map, we need to give '`equirectangular`' only. if we don't want flatten map then I can keep **equalEarth** and **naturalEarth1**. Should we restrict flatten for Global map?
> 
>     3. ok got it. Are they over written at stoybook ?

1. For example purposes the values are random, but these will be real values in real maps. Showing the scaled value in datalabels does not really provide any value. I think remove datalabels entirely from Choropleth, only use them on BubbleMap to show City names or similar (like the geo plugin example).
2. We can't restrict anything, we are just choosing the default. Carbon Charts for example uses `naturalEarth1` as the default, which looks the best in my opinion. 
3. Yes. The load order for options configs is:
   1. globalOptions.js
   2. globalOptionsRadial.js/NonRadial.js
   3. chartType/{chartType}.js
   4. options passed to kd-chart component

2023-11-02 17:47 UTC, maulik-thaker1 commented
> 2\. naturalEarth1



> > ```
> > 1. there's no actual value in dataset I guess. We are generating random value by giving `value: Math.random() * 10` kind of random value generation
> > 
> > 2. If we do projection: "`equalEarth`" and "`naturalEarth1`" then map is not gonna flatten. For flatten world map, we need to give '`equirectangular`' only. if we don't want flatten map then I can keep **equalEarth** and **naturalEarth1**. Should we restrict flatten for Global map?
> > 
> > 3. ok got it. Are they over written at stoybook ?
> > ```
> 
> 1. For example purposes the values are random, but these will be real values in real maps. Showing the scaled value in datalabels does not really provide any value. I think remove datalabels entirely from Choropleth, only use them on BubbleMap to show City names or similar (like the geo plugin example).
> 2. We can't restrict anything, we are just choosing the default. Carbon Charts for example uses `naturalEarth1` as the default, which looks the best in my opinion. It looks more flat with the outline removed.
> 3. Yes. The load order for options configs is:
>    
>    1. globalOptions.js
>    2. globalOptionsRadial.js/NonRadial.js
>    3. chartType/{chartType}.js
>    4. options passed to kd-chart component

1. Ok gotcha. I'm removing dataLables from choropleth and only apply on Bubblemap
2. Ok. I made it `naturalEarth1` and it's looks like follow with outline removed :

<img width="1109" alt="Screenshot 2023-11-02 at 11 13 32 PM" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/140634142/e6749850-1fa6-4dd1-a09c-364e53804875">

 
 I pushed code with these changes. Can you approve now ?

2023-11-02 18:27 UTC, brian-patrick-3 commented
> I pushed code with these changes. Can you approve now ?

1. The default config changes still need to be moved into the chartType JS config files.
2. Bubble Map datalabels font size seems like it may bee too small for accessibility.

2023-11-03 06:50 UTC, maulik-thaker1 commented
> > I pushed code with these changes. Can you approve now ?
> 
> 1. The default config changes still need to be moved into the chartType JS config files. Use "World" as the default, and make it the first story.
> 2. Bubble Map datalabels font size seems like it may bee too small for accessibility.
> 3. Stories are still under "Proof of Concept", let's change that if these are ready.

1. Done. Added datalable plugin into bubblemap default config file named : bubbleMap.js
2. Done. Changed to 12
3. What should be the name? **Third-Party Charts** or **Others**?

2023-11-03 14:50 UTC, brian-patrick-3 commented
>     3. What should be the name? **Third-Party Charts** or **Others**? As on welcome page it's named **Third-party-charts** so I named accordingly.

Third-Party Charts is a good distinction. However, Tree Map is not ready yet as far as I know, and should remain under Proof of Concept.

Also, the Choropleth defaults (World) for projection, showOutline, etc still need to be moved to the chartType js config file. Then you'll have to adjust the options for the US and World stories.

2023-11-03 15:11 UTC, maulik-thaker1 commented
> > ```
> > 3. What should be the name? **Third-Party Charts** or **Others**? As on welcome page it's named **Third-party-charts** so I named accordingly.
> > ```
> 
> Third-Party Charts is a good distinction. However, Tree Map is not ready yet as far as I know, and should remain under Proof of Concept.
> 
> Also, the Choropleth defaults (World) for projection, showOutline, etc still need to be moved to the chartType js config file. Then you'll have to adjust the options for the US and World stories.

We didn't touched much to Treemap yet and on demo also no one mentioned to extend this. So, I am considering it's done. Maybe enhancement can open more explorations on this or later phase I guess.

oh I guess  **showOutline** and **showGraticule** is only remaining. I moved it to  chartType.js. Also adjusted storybook options to US and World stories.

[A] US options: 

<img width="1552" alt="Screenshot 2023-11-03 at 8 39 33 PM" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/140634142/2008b22b-4395-4d8a-84a3-a618b5031d39">


[B] World options: 

<img width="1545" alt="Screenshot 2023-11-03 at 8 40 53 PM" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/140634142/39529ca8-b629-4106-bac3-33cde31d11d4">

2023-11-03 15:34 UTC, brian-patrick-3 commented
Tree Map is still Proof of Concept, since design has not touched it yet.

You forgot to change the projection default to naturalEarth1 in the config. Once that is done, you can remove any default options from the World story.

2023-11-03 18:22 UTC, maulik-thaker1 commented
> Tree Map is still Proof of Concept, since design has not touched it yet.
> 
> You forgot to change the projection default to naturalEarth1 in the config. Once that is done, you can remove any default options from the World story.

I am waiting for confirmation for TreeMap is still POC or not. Apart from that I removed default options from World story & added projection in config.

2023-11-04 19:37 UTC, brian-patrick-3 approved these changes

2023-11-06 05:41 UTC, merged

2023-11-06 05:42 UTC, maulik-thaker1 commented
I merged this as I no one replies for Treemap. If anything coming then we'll look do in Prague release.

2023-11-06 05:49 UTC, brian-patrick-3 commented
:tada: This PR is included in version 1.0.0-beta.15 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-charts/v/1.0.0-beta.15)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-charts/releases/tag/v1.0.0-beta.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-13 15:05 UTC, brian-patrick-3 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-charts/v/1.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-charts/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: